# Generated by Django 3.2.8 on 2021-12-30 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='middle_initial',
            field=models.TextField(max_length=3),
        ),
    ]
