# Generated by Django 3.2.8 on 2021-12-30 04:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MvnsCollectedData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderNumber', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='orderNumber')),
                ('dateDataCollected', models.DateField(auto_now_add=True, verbose_name='dateDataCollected')),
                ('timeDataCollected', models.TimeField(auto_now_add=True, verbose_name='timeDataCollected')),
                ('motoristFirstName', models.CharField(max_length=50, verbose_name='motoristFirstName')),
                ('motoristMiddleInitial', models.CharField(blank=True, max_length=3, verbose_name='motoristMiddleInitial')),
                ('motoristLastName', models.CharField(max_length=50, verbose_name='motoristLastName')),
                ('plateNumber', models.CharField(max_length=10, verbose_name='plateNumber')),
                ('dbReading', models.DecimalField(decimal_places=0, max_digits=5, verbose_name='dbReading')),
                ('distance', models.DecimalField(decimal_places=0, max_digits=5, verbose_name='distance')),
                ('officerName', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL, verbose_name='officerName')),
            ],
        ),
    ]
